# Generated by Django 5.0.4 on 2024-04-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='price',
        ),
        migrations.AddField(
            model_name='flower',
            name='price_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price for size L'),
        ),
        migrations.AddField(
            model_name='flower',
            name='price_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price for size M'),
        ),
        migrations.AddField(
            model_name='flower',
            name='price_s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price for size S'),
        ),
        migrations.AddField(
            model_name='flower',
            name='price_xl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price for size XL'),
        ),
        migrations.AddField(
            model_name='flower',
            name='price_xxl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price for size XXL'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(upload_to='flower_images/'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'SM'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('S M', 'S M'), ('M L', 'M L'), ('L XL', 'L XL'), ('XL XXL', 'XL XXL'), ('S M L', 'S M L'), ('M L XL', 'M L XL'), ('L XL XXL', 'L XL XXL'), ('S M L XL', 'S M L XL'), ('M L XL XXL', 'M L XL XXL'), ('S M L XL XXL', 'S M L XL XXL')], max_length=12),
        ),
    ]
